// Generated by CoffeeScript 1.7.1
var Ractive, RactiveCompiler, sysPath;

Ractive = require('ractive');

sysPath = require('path');

module.exports = RactiveCompiler = (function() {
  RactiveCompiler.prototype.brunchPlugin = true;

  RactiveCompiler.prototype.type = 'template';

  RactiveCompiler.prototype.extension = 'rac';

  RactiveCompiler.prototype.pattern = /\.(?:rac|ractive)$/;

  function RactiveCompiler(config) {
    this.config = config;
    null;
  }

  RactiveCompiler.prototype.compile = function(data, path, callback) {
    var err, error, result, template;
    try {
      template = JSON.stringify(Ractive.parse(data));
      return result = "module.exports = " + template + ";";
    } catch (_error) {
      err = _error;
      return error = err;
    } finally {
      callback(error, result);
    }
  };

  return RactiveCompiler;

})();
